name: Test
on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!.github/**'
      - '!.gitignore'
      - '.github/workflows/test.yml'
  workflow_dispatch:

jobs:
  nix:
    name: go test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v16
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests
        run: nix-shell --pure --run 'go test'
  windows:
    name: go test (Windows)
    runs-on: windows-2022
    steps:
      - name: Install Go
        uses: actions/setup-go@v3.2.1
        with:
          go-version: "1.19"
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests
        run: go test
